### ISSUE TITLE
error in step 4

### ISSUE THREAD

**Issue by ubaidillahumar** [protegeproject/cellfie-plugin#104]
when I follow step 4 display error cannot cast uk.ac.manchester.cs.owl.owlapi.OWL ClassImpl to org.semanticweb. how to fix this problem?

**Comment by csnyulas** [comment]
It is not clear what Step 4 you are referring to. Are you talking about Step 4 of the Grocery Tutorial?
https://github.com/protegeproject/cellfie-plugin/wiki/Grocery-Tutorial#step-4---creating-some-value-restriction-axiom
Which version of Protégé are you using?
Which version of Cellfie plug-in are you using? (You can check it through the `Help -> About` menu)
Have you downloaded the files specified in the "Setup and Installation" section of the tutorial and opened the `posc-groceries.owl` ontology?

**Comment by ubaidillahumar** [comment]
yes, step 4 of the grocery tutorial, I follow this step but display this error.

I use Protege 5.1.0. and cellfie plug-in  version 2.1.0

**Comment by ubaidillahumar** [comment]
I want to populate an individuals ontology with data in a text of excel file, can I use this plugin?

**Comment by csnyulas** [comment]
Here are a few questions to debug the issue:
- Did you have previous versions of Protege installed?
- Can you provide us the logs (or a copy of the terminal) containing the error messages? In absence of that it is really hard to tell what is going on.
- Did you load the `posc-groceries.owl` ontology before following the steps of the tutorial?
- Which Excel file and JSON file are you trying to use with Cellfie?

**Comment by csnyulas** [comment]
You can use the Cellfie plugin to import individuals, classes and other OWL statements from an Excel file. If you have your data in a text file, you should first create a well formatted Excel file from it. We have an issue (#35) on our tracker to support CSV files in the future.

**Comment by ubaidillahumar** [comment]
thanks you csnyulas, I miss load the posc-groceries.owl ontology before following the steps of the tutorial, I use my own ontology. now this problem is clear.

**Comment by ubaidillahumar** [comment]
sorry csnylas, have you tutorial to populate an individuals ontology from excel file? thanks for your support.

**Comment by csnyulas** [comment]
OK. I close this issue, then. Feel free to reopen it, if you still experience the problem, or create a new issue, if you experience a different problem. In any case, please provide the error logs, and an accurate description of the steps that bring you to the error.  Thanks.

**Comment by csnyulas** [comment]
Steps 7, 8 and 9 of the tutorial show you how to import individuals.
The [MappingMaster DSL](https://github.com/protegeproject/mapping-master/wiki/MappingMasterDSL) gives you a detailed description of all the features of the mapping language that you can use with Cellfie, including everything you can do to create and describe individuals.

**Comment by ubaidillahumar** [comment]
thanks you csnyulas
