### ISSUE TITLE
Importing Data properties from Excel shows Error: " Expecting Literal for some values data restrictions" 

### ISSUE THREAD

**Issue by pranav0008** [protegeproject/cellfie-plugin#116]
I took all the Data properties in a separate column in Excel and tried to import them in 'Protégé' as we import Object properties.
I created a dummy class in my ontology firstly
{
Class: Dummy
SubClassOf: @G* (DataProperty) some owl:Thing 
}
Error : Expecting Literal for some values data restriction ( @G* (Dataproperty) some owl:Thing )
Can anyone tell me how to remove this error and what it means ?

**Comment by martinjoconnor** [comment]
A some values restriction on a data property cannot be a class. 

https://www.w3.org/TR/owl-ref/#someValuesFrom-def

**Comment by pranav0008** [comment]
then how do we import multiple data properties into Protégé from Excel other than typing each property manually in the Protégé editor?

**Comment by csnyulas** [comment]
As @martinjoconnor mentioned, the problem was that the some values from a dataproperty cannot be a class (i.e. `owl:Thing`). It could be `xsd:string` instead, for example. Like
```
  SubClassOf: @g* (DataProperty) some xsd:string
```

**Comment by pranav0008** [comment]
thank you, I understood the concept and the problem is solved
