### ISSUE TITLE
how to attach a link for a PDF document in an Ontology in Protege.

### ISSUE THREAD

**Issue by pranav0008** [protegeproject/cellfie-plugin#117]

**Comment by csnyulas** [comment]
The best would be to use an annotation property (such as `rdfs:seeAlso`) to the URL of the PDF file, like this:
![image](https://user-images.githubusercontent.com/2441046/29259354-329baba0-8077-11e7-966c-946789e9c608.png)

**Comment by csnyulas** [comment]
BTW, you could even refer to a local file (see discussion [here](https://mailman.stanford.edu/pipermail/protege-user/2017-June/thread.html#7312)), but that would not be very portable.
