### ISSUE TITLE
Importing an entity with "() " , makes the whole entity in Quotes

### ISSUE THREAD

**Issue by pranav0008** [protegeproject/cellfie-plugin#120]
For Eg: if an entity: 
Protege(Cellfie) gets imported(using Cellfie) into Protege as 'Protege(Cellfie)' and after adding it once this entity shows error if I try to use this Entity in anything else.
It becomes like it can only be defined once and after that no changes can be made. 
Also if an Entity is  Protege: Cellfie , it cannot be imported to Protege using Cellfie, shows error
What is the proper way to importing this entities in Protege ?

**Comment by csnyulas** [comment]
You can specify an encoding of the names that would not preserve these special characters, such as `(`, `)` or `:`. I would recommend `mm:hashEncode`, if you need to run the rules more than once.

For more on please check out:
https://github.com/protegeproject/mapping-master/wiki/MappingMasterDSL#iris
