### ISSUE TITLE
How to code for Creating Dataproperty heirarchy and Object Property heirarchy in Cellfie?

### ISSUE THREAD

**Issue by pranav0008** [protegeproject/cellfie-plugin#121]
I have an Excel in which there are a lot of Data Properties which have a lot sub-properties.
I know how to create DataProperty in Cellfie but the function ( SubPropertyOf ) doesn't work in cellfie.
I have to do it manually in Protege which makes it look like labor work :( .

**Comment by csnyulas** [comment]
It is true. Sorry about the inconvenience. This is a limitation of MappingMaster, and we have an issue created for it here: protegeproject/mapping-master/issues/9. So I'll close this issue.

PS: Once you create all the properties with Cellfie, reorganizing them in a hierarchy in Protege, would involve less effort then creating all the properties manually, one by one. Which reminds me that actually you can create a property hierarchy easily in Protege. Select `owl:topDataProperty` (or whatever you want to be the root of your property hierarchy, and either right click and select `Add Sub-properties...` or open the `Tools --> Create data property hierarchy...` menu. In the wizard that pops up, enter (or copy-paste from your spreadsheet or text file), a tab indented list of property names. Click `Continue`, then `Finish` and you got your property hierarchy.

**Comment by pranav0008** [comment]
okay thanks a bunch

**Comment by csnyulas** [comment]
I observed the same problem. Basically if I update the OAF plugin from 
version 1.0.0 to 1.1.0, the new jar file will be downloaded and copied 
in the plugins folder, but Protege continue to think it still has v.1.0.0.

It may be because of this line in the META-INF/MANIFEST.MF file:
Bundle-Version: 1.0.0

Csongor

**Comment by xendat** [comment]
> I have an Excel in which there are a lot of Data Properties which have a lot sub-properties.
> I know how to create DataProperty in Cellfie but the function ( SubPropertyOf ) doesn't work in cellfie.
> I have to do it manually in Protege which makes it look like labor work :( .

Hi, @pranav0008 , you mentioned here that you know how to create DataProperty in Cellfie, but I have not been able to to make that work yet in Protege 5.x.  Could you please share how you did it?  I would be very grateful, as I have an Excel with a bunch of attributes and data properties with their definitions for my classes that I would like to load into my ontology.  

Thanks so much!

**Comment by martinjoconnor** [comment]
Mapping Master does not currently support the declation of object or datatype properties:

https://github.com/protegeproject/mapping-master/wiki/MappingMasterDSL#manchester-syntax-coverage
