### ISSUE TITLE
DL learner 0.8 plugin not able to run successfully with protege 5.0 

### ISSUE THREAD

**Issue by pranav0008** [protegeproject/cellfie-plugin#123]
Only DL query is working properly in  Protege. Is there any other method by which we can make a Machine learning Model ( Ontology learning ) in Protege ?
Or is there any other software where ML can be used in making Ontology if Protege is not able to fulfill the purpose ?
I am aiming to build a ML model which could Automatically or Semi-Automatically make ontology from Excel or CSV files.  I want to reduce the work in case where we have a lot of excel sheets.

**Comment by martinjoconnor** [comment]
You should post this type of question to the Protege mailing list:

https://protege.stanford.edu/support.php
