### ISSUE TITLE
Object Property Issue

### ISSUE THREAD

**Issue by Gautamshahi** [protegeproject/cellfie-plugin#134]
Hi, 

While I am loading the data for the object property I am getting the value (which should e object property) of that column in a scaretted way as in the picture, administrative, administrative, Ahmedabad etc as an individual. 
![image](https://user-images.githubusercontent.com/3966230/39078800-b0059b1c-452c-11e8-8289-93860dce2d7c.png)

The code I used is 
{"Collections":[
{"sheetName":"Earthquake_EMDAT",
"startColumn":"A","endColumn":"N",
"startRow":"2","endRow":"+","comment":"",
"rule":"Individual: @A* \n    Types: Earthquake\n  
  Facts: date @B*,\n              
  country @C*,\n               
  magnitude @I*,\n           
  location @E*,\n           
  death @O*,\n             
  disasterNumber @T*","active":true}]}

My data is as below
![image](https://user-images.githubusercontent.com/3966230/39078875-e89f0322-452d-11e8-8fbf-e40d45620280.png)

**Comment by Gautamshahi** [comment]
Can you please why I am getting the values "Ahmedabad", "Andaman" along with individuals? These values are city name under object properties city.

**Comment by martinjoconnor** [comment]
Can you post this question (with perhaps a bit more context) to the Protege mailing list.

https://protege.stanford.edu/support.php

You will likely get a quick response there.
