### ISSUE TITLE
Missing required prefix when trying to use dates for object properties or Individuals

### ISSUE THREAD

**Issue by vipeReu** [protegeproject/cellfie-plugin#140]
I have a couple of data sets in excel and one of them had columns with dates stored.
I used the instructions mentioned in #59 to change the dates and it worked fine.
When creating the transformation rules declaring the dates as data properties with the type xsd:dataTime, it works as intended.
But I can't use the dates in ObjectProperties or in the Individuals declaration.

As an example if I try to use mm:prepend to prepend a date from column @B to something from column @E (that is not a date) it will throw me a "Missing required prefix".
Changing the @B to a different column source that doesnt contain dates makes the transformation work with no issues.

Is is intended that I can't use dates in the ISO8601 format in object properties and individuals or is it something else?

**Comment by martinjoconnor** [comment]
I am not fully following. Can you give some example cell value and Mapping Master expressions that illustrate what you are saying.

**Comment by martinjoconnor** [comment]
Ideally, post a spreadsheet and file containing Mapping Master expressions so that we can quickly identify the issue.

**Comment by vipeReu** [comment]
I will do so tomorrow since I will be busy till then. Thank you for the quick reply :-)

**Comment by csnyulas** [comment]
Another quick question, to try to understand the problem: 
Are you trying to use the dates as part of the IRI of the newly created individuals (or object properties)?
That may not be a good idea. You should at least **strip the colons** from them (maybe by preprocessing them in another column of the spreadsheet, if doing the processing in MM is too difficult), because those would likely cause a confusion for the entity  matcher.

**Comment by vipeReu** [comment]
> Another quick question, to try to understand the problem:
> Are you trying to use the dates as part of the IRI of the newly created individuals (or object properties)?
> That may not be a good idea. You should at least **strip the colons** from them (maybe by preprocessing them in another column of the spreadsheet, if doing the processing in MM is too difficult), because those would likely cause a confusion for the entity matcher.

exactly what I attempted to do!
I will try to get rid of the colons if I get back to my project and will write here if I have new information on the matter.
Thanks in advance :-)

**Comment by vipeReu** [comment]
> Another quick question, to try to understand the problem:
> Are you trying to use the dates as part of the IRI of the newly created individuals (or object properties)?
> That may not be a good idea. You should at least **strip the colons** from them (maybe by preprocessing them in another column of the spreadsheet, if doing the processing in MM is too difficult), because those would likely cause a confusion for the entity matcher.

So I managed to get back to my data today and removing the colons fixed the issue. It apparently really was the entity matcher being confused by the colons inside the particular data. Thanks for the tip and the quick replies from everyone :-)
