### ISSUE TITLE
"Facts" cannot be some special values

### ISSUE THREAD

**Issue by imane0897** [protegeproject/cellfie-plugin#142]
I'm just using the case in the [tutorial](https://github.com/protegeproject/cellfie-plugin/wiki/Grocery-Tutorial). I typed the following in the Transformation Rule Editor and get an error.

```
Individual: @A*
   Types: NOT
```

![image](https://user-images.githubusercontent.com/14917020/55396790-4d6d7900-5577-11e9-8076-07788bcc758c.png)

I also test "OR" and "AND" and they are not allowed as values of "Type" either. This seems to be wired since Protege allows "class" value to be "OR", "AND" and "NOT".

**Comment by martinjoconnor** [comment]
Those are language keywords so cannot be used as entity names.

From a modelling point of view I don't think it would be a good idea to have a class called NOT, OR, or AND.
