### ISSUE TITLE
Standalone usage

### ISSUE THREAD

**Issue by neobernad** [protegeproject/cellfie-plugin#146]
Hi,

Is it possible to run this plugin without going through Protégé, as a standalone `jar`?

Thanks,
José Antonio

**Comment by martinjoconnor** [comment]
There is an example repo called mapping-master-example that illustrates API-level usage. 

https://github.com/protegeproject/mapping-master-example/blob/master/src/main/java/org/mm/example/MMExample.java

**Comment by neobernad** [comment]
Thank you so much for your reply @martinjoconnor. It was really helpful!
