### ISSUE TITLE
Issue while adding the object property 

### ISSUE THREAD

**Issue by Gautamshahi** [protegeproject/cellfie-plugin#147]
Hi,

There is an object property, location, While importing the data for the object property. The value for the object property coming as an individual. For example "Ahmedabad", "Andaman" are along with other individuals.

Can you please explain the issue?

https://user-images.githubusercontent.com/3966230/39078800-b0059b1c-452c-11e8-8289-93860dce2d7c.png

The code I used is
{"Collections":[
{"sheetName":"Earthquake_EMDAT",
"startColumn":"A","endColumn":"N",
"startRow":"2","endRow":"+","comment":"",
"rule":"Individual: @A* \n Types: Earthquake\n
Facts: date @b*,\n
country @C*,\n
magnitude @i*,\n
location @e*,\n
death @o*,\n
disasterNumber @t*","active":true}]}

My data is as below

https://user-images.githubusercontent.com/3966230/39078875-e89f0322-452d-11e8-8fbf-e40d45620280.png

**Comment by martinjoconnor** [comment]
Can you post this question to the Protege mailing list.

https://protege.stanford.edu/support.php

I also don't understand the issue. You say "The value for the object property coming as an individual." 

In OWL the value for an object property is an individual.

**Comment by Gautamshahi** [comment]
Hi, I have resolved it.

Thank you for your time. please close the issue.
