### ISSUE TITLE
Check for unsaved changes when closing Cellfie

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/cellfie-plugin#15]
When user tries to close Cellfie, there should be a check on whether there is any unsaved change to the mapping expressions, and in case there is, a dialog should prompt the user to decide whether he or she wants to save or drop the changes, or resume editing.

**Comment by csnyulas** [comment]
Related to #14

**Comment by csnyulas** [comment]
Related to #13

**Comment by johardi** [comment]
Implemented at https://github.com/protegeproject/cellfie-plugin/commit/1458cd12de910073197d3742e9602070f65c3e41

**Comment by johardi** [comment]
The dialog doesn't appear when users click on the upper left close [x] button

**Comment by johardi** [comment]
Fixed at https://github.com/protegeproject/cellfie-plugin/commit/a86bc4589f0b04da95faf8b5e93904464f40007b
