### ISSUE TITLE
Annotations on object properties

### ISSUE THREAD

**Issue by neobernad** [protegeproject/cellfie-plugin#150]
Hello all,

I would be interested in creating annotations on object properties as in:

```cypher
meters -[transforms_to (annotation(factor:1000))]-> kilometers
```
In order to say that meters can be transformer into kilometers by multiplying by a factor of 1000.
Is this doable in the plugin? I have seen this issue #101 which is kind of related but for annotations instead of object properties.

Thanks,
José Antonio

**Comment by martinjoconnor** [comment]
The Manchester Syntax (on which the Mapping Master language used by Cellfie is based) does not have mathematical operators.   

You could use SWRL to perform these types of operations after you import your content:

https://github.com/protegeproject/swrlapi/wiki/SWRLLanguageFAQ

**Comment by neobernad** [comment]
Hi @martinjoconnor,

Thanks for your quick reply. I did not mean to explicitly perform the mathematical operation, but to create an annotation on the object property, the `factor:1000` was just as an example. Are annotations on object properties possible?

**Comment by martinjoconnor** [comment]
Unfortunately, the Mapping Master language does not currently support clauses for declaring OWL properties. If it did you could some something like the following:

```
ObjectProperty: hasWife
    Annotations: creator Bob
```

**Comment by ZaidaMoraAlvarez** [comment]
Hello, I am interested in knowing if the definitions of classes can be loaded from an excel sheet in the Annotations section? thanks

**Comment by martinjoconnor** [comment]
I don't understand the question. Can you provide an example.

The Protege mailing list is a better place to ask general questions:

https://protege.stanford.edu/support.php
