### ISSUE TITLE
Grocery tutorial throws error

### ISSUE THREAD

**Issue by ghost** [protegeproject/cellfie-plugin#151]
While following tutorial: https://github.com/protegeproject/cellfie-plugin/wiki/Grocery-Tutorial, user is asked to download Grocery ontology (https://raw.githubusercontent.com/protegeproject/github-wiki-resources/master/cellfie/Working-Samples/posc-groceries.owl) and Excel workbook (https://raw.githubusercontent.com/protegeproject/github-wiki-resources/master/cellfie/Working-Samples/grocery-item.xlsx). 

Tutorial works fine till step 2. Step 3 fails with following error "The expected entity name "GroceryItem" doesn't exist in ontology". Step 3 mandates that ontology file already be loaded (copy/pasted: **In the example above, the class GroceryItem must already be typed int the ontology.**). Loading of Grocery ontology is not explained in step 1 or 2. At least, tutorial could have provided another link on loading Grocery Ontology prior to step 1 or at step 3. 

Expected: A short note or link to load Ontology files.

**Comment by johardi** [comment]
Hi, thanks for using the tutorial. The instruction to load the ontology is already mentioned in Step 1, the first sentence:
```
Open the grocery ontology using Protégé by double-clicking the OWL file.
```

I think it doesn't cover the case where users already open Protégé and start doing the tutorial. I've added a sentence to load the ontology to cover this extra case. I've fixed also the typo in Step 3.
