### ISSUE TITLE
Bug? Axioms 'SubClassOf' with class expression are not generated with cell values

### ISSUE THREAD

**Issue by constnick** [protegeproject/cellfie-plugin#156]
Rule:
```
Class: Class1
SubClassOf: (dataProp1 value @A1)
SubClassOf: (dataProp1 value 111)
```
Cell A1 has any simple value.
Axioms generated:
```
Class: Class1
Class1 SubClassOf dataProp1 value 111
```
Test files in zip:
[CellfieTest.zip](https://github.com/protegeproject/cellfie-plugin/files/5979769/CellfieTest.zip)

**Comment by martinjoconnor** [comment]
Have you tried giving an explicit type to the referenced cell, e.g, 

Class: Class1
SubClassOf: (dataProp1 value @A1(xsd:integer))
SubClassOf: (dataProp1 value 111)

It looks like it is confused and failing silently when it does not know the type of the value.

**Comment by constnick** [comment]
Thank you, it works.

(I used example from MappingMasterDSL wiki, there is no explicit type in same case.)
