### ISSUE TITLE
Regarding - Create axioms from excel workbook 

### ISSUE THREAD

**Issue by WarisBunglawala** [protegeproject/cellfie-plugin#159]
When i try to import the excel workbook to generate mapping rules using Cellfie one of the column in workbook is of date and in excel it shows correctly (ex. 04-07-2001) but in mapping master that data is displayed in some numbers (ex. 37076)

**EXCEL correct data ss:**
![correct display by excel](https://user-images.githubusercontent.com/46418493/150958531-1a0f5e92-0048-4c30-b04c-66d9358f1020.png)

**Cellfie Wrong Data display.**
![wrong display](https://user-images.githubusercontent.com/46418493/150958539-c7c43b93-e483-41b7-ace9-5aa9d76d544e.png)

**Comment by martinjoconnor** [comment]
Can you upload an example spreadsheet that illustrates this issue.

**Comment by WarisBunglawala** [comment]
> Can you upload an example spreadsheet that illustrates this issue.
 Sure here is a demo excel sheet.

[fisrt-500 - Copy.xlsx](https://github.com/protegeproject/cellfie-plugin/files/7938771/fisrt-500.-.Copy.xlsx)

**Comment by martinjoconnor** [comment]
I have fixed this issue. I will be generating a new Cellfie release in a few days.

**Comment by WarisBunglawala** [comment]
Thanks a Lot, Waiting for a new release.

**Comment by martinjoconnor** [comment]
A new 2.1.1 release should be available. Go to the File->Check for plugins... in Protege to get the latest Cellfie.

**Comment by WarisBunglawala** [comment]
I have installed new release and checked, it worked.
Thank you 👍 :)
