### ISSUE TITLE
Annotations as rdfs:comments

### ISSUE THREAD

**Issue by ZaidaMoraAlvarez** [protegeproject/cellfie-plugin#161]
Hello, I am interested in knowing if the definitions of classes can be loaded from an excel sheet in the Annotations section? thanks

**Comment by martinjoconnor** [comment]
I don't understand the question. Can you provide an example.

The Protege mailing list is a better place to ask general questions:

https://protege.stanford.edu/support.php

**Comment by ZaidaMoraAlvarez** [comment]
Thanks for your communication. I have classes in an excel sheet in column A and I have already generated axioms of them with object properties and data properties using Cellfie to create modules of an ontology. Cellfie has been very useful to me. However, in one of the columns of the excel sheet I have the respective descriptions that are usually noted as comments in the Protégé Annotations window. I have searched in the Cellfie tutorials if these annotations of the rdfs:comments type can also be captured with Cellfie. I am interested in knowing if I can capture this type of annotations with Cellfie because it would save a lot of capture time and avoid typing errors.

**Comment by ZaidaMoraAlvarez** [comment]
![image columns import Cellfie](https://user-images.githubusercontent.com/71114800/183309660-e923ac90-2118-4823-b8d2-0ef33480eff4.JPG)

**Comment by ZaidaMoraAlvarez** [comment]
![image frame annotations dude cellfie](https://user-images.githubusercontent.com/71114800/183309857-89974e69-8110-42ca-a4ca-bb143ad1a5a4.png)

**Comment by ZaidaMoraAlvarez** [comment]
Thank you very much!! I find an example of annotations in
![image Cellfie annotation of comments as definition of classes in excel](https://user-images.githubusercontent.com/71114800/183314151-c4570c66-3d80-4161-a462-7cb23b0161c6.JPG)
 #70. I already type the annotation and in all classes the axiom gives the correspondient rdfs:comment

**Comment by ZaidaMoraAlvarez** [comment]
Thank you martinjoconnor by the reference. Best regards!!
