### ISSUE TITLE
No "> Create axioms from Excel workbook..." option in "Tools"

### ISSUE THREAD

**Issue by lmwishnie** [protegeproject/cellfie-plugin#171]
I downloaded and installed Cellfie per the instructions and saved the .jar file in the plugins folder of my Protege installation.
However, when I start Protege, there is no option to use Cellfie -- the "> Create axioms from Excel workbook..." option doesn't appear in "Tools". Any advice? Thank you!

**Comment by martinjoconnor** [comment]
Cellfie has been pre-installed with Protege for quite a few years. 

Are you using the latest 5.6.3 version of Protege?  

You can also select the File->Check for plugins... option in Protege to make sure you are using the latest version of Cellfie.

**Comment by lmwishnie** [comment]
I updated my version and that fixed the problem. I was still on 5.5.0. Thanks, Martin.
