### ISSUE TITLE
After deleting a transformation rule, select a new one

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/cellfie-plugin#21]
It would be nice if after deleting a transformation rule, another one would be automatically selected. Let's say, the rule that took the place of the previously selected one. I.e. if we have 10 rules and the third one is deleted, the rule that was previously the fourth and now it became the third should be selected. If the last rule is deleted, the previous rule (the new last rule) should be selected.

This behavior would allow the speedy deletion of multiple rules.

**Comment by johardi** [comment]
Implemented at https://github.com/protegeproject/cellfie-plugin/commit/382ecc17d5eecc5a7b2d91f523ef880e05dbbd95 and https://github.com/protegeproject/cellfie-plugin/commit/cb55f5888a84e351ebbb0b25e4beb74379049a85
