### ISSUE TITLE
Misbehavior of the "Add" transformation rule button when a transformation rule is already selected

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/cellfie-plugin#23]
Trying to add a new transformation rule by pressing the "Add" button while an existing transformation rule is selected, would **replace** the old rule with the new one (i.e. we will loose the selected rule).

**Comment by johardi** [comment]
Fix at https://github.com/protegeproject/cellfie-plugin/commit/19426b7a1e04b40587cf58bc168ff391c8e95c1d
