### ISSUE TITLE
Missing path separator in log file name

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/cellfie-plugin#28]
After pressing on Generate axioms I got this:
![screenshot from 2015-10-02 14 43 31](https://cloud.githubusercontent.com/assets/2441046/10258581/338599b2-6914-11e5-9372-bfea136eeede.png)

**Comment by johardi** [comment]
Fix at https://github.com/protegeproject/cellfie-plugin/commit/9e85122aae4a45f24531366463bfae0274b47f04
