### ISSUE TITLE
Unable to open XLS files

### ISSUE THREAD

**Issue by marcosmro** [protegeproject/cellfie-plugin#30]
I tried to open a .xsl file but the UI did not allow me to select it. However, it allows me to open .xslx files.

![screen shot 2015-10-09 at 3 54 30 pm](https://cloud.githubusercontent.com/assets/7634440/10407327/416f68ac-6e9e-11e5-8cfe-fbe8a561217f.png)

**Comment by csnyulas** [comment]
It works for me in Linux, but in order to see files that have extension different other than .xlsx, I need to change the "Files of Type" selection to "All Files".

![screenshot from 2015-10-09 16 18 37](https://cloud.githubusercontent.com/assets/2441046/10407574/f6eac804-6ea1-11e5-851c-9e28fec2e1a5.png)

**Comment by marcosmro** [comment]
Thanks, Csongor. However, I cannot see that option in Mac:

<img width="704" alt="screen shot 2015-10-09 at 4 48 18 pm" src="https://cloud.githubusercontent.com/assets/7634440/10407860/aeb7a95e-6ea5-11e5-994d-e95c230e52e8.png">

**Comment by johardi** [comment]
Right now Cellfie supports only .xlsx extension. Perhaps the quick solution is to save as XLSX file using Excel

**Comment by martinjoconnor** [comment]
In general though XLS, XLSX (and perhaps CSV) should be available defaults. It might be worth looking at the formats that POI supports by default and adding those as available default options.

**Comment by johardi** [comment]
Fix at https://github.com/protegeproject/cellfie-plugin/commit/292555785d57b2d52f0af9fba9cbf21dcfad8e2e

(Opening new ticket for CSV file support https://github.com/protegeproject/cellfie-plugin/issues/35)
