### ISSUE TITLE
NullPointerException when opening XLSX file

### ISSUE THREAD

**Issue by marcosmro** [protegeproject/cellfie-plugin#31]
I tried to open the enclosed spreadseet [1] and received the following error message:

![screen shot 2015-10-09 at 4 02 15 pm](https://cloud.githubusercontent.com/assets/7634440/10407434/6ee91c00-6e9f-11e5-9f47-269c7ac9ef8c.png)

![screen shot 2015-10-09 at 4 03 06 pm](https://cloud.githubusercontent.com/assets/7634440/10407437/760e467c-6e9f-11e5-9844-ba8c75b8a471.png)

[1] https://drive.google.com/file/d/0B9wKatqya2cjQ2Rpelp5M00xbEk/view?usp=sharing

**Comment by johardi** [comment]
I found the culprit. So it seems there are blank rows in the middle of the spreadsheet (i.e., row 189, 215, 218) and they are causing the exception. A quick fix is to remove all these rows and try to reload the file. In the meantime, I'll fix the code to cope this issue.

**Comment by johardi** [comment]
Fix at https://github.com/protegeproject/cellfie-plugin/commit/dfb5c74aa687a20116c0c222cc67a3abd762cfa5

**Comment by marcosmro** [comment]
It works. Thanks!
