### ISSUE TITLE
Using some prefixed annotation property names in transformation rules throws errors

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/cellfie-plugin#38]
![screenshot 2015-10-22 2321](https://cloud.githubusercontent.com/assets/2441046/10700135/960a65f6-7970-11e5-8d7b-d1032e3af251.png)
When trying to generate the axioms for the following transformation rule:

```
Individual: @A*
    Types: S
    Annotations: rdfs:label @C*
```

Cellfie/MappingMaster complains that it expects something else instead of `rdfs:label`.

Just to make sure that this should really run, we defined the `rdfs` prefix in the ontology manually.
Using other, locally defined, annotation properties work fine.
Error may be related to use of prefixed names in general, for any type of entities.

**Comment by johardi** [comment]
This is a known bug as well as Cellfie limitation. This happens because `rdfs:label` is a keyword in the mapping/transformation syntax. Other rdfs annotation properties, e.g., `rdfs:comment` should work fine.

**Comment by martinjoconnor** [comment]
If should be fixable, though. The parser needs to anticipate this token when parsing an annotation and and the tree processor needs to handle it also.

This is probably the most common annotation property so handling it would be good.

**Comment by csnyulas** [comment]
Actually,  if I use `rdfs:seeAlso` or `rdfs:comment` properties I get a different error message ("The AnnotationProperty rdfs:comment does not exist in the ontology"), which is maybe even more relevant to this issue. As I mentioned in the initial issue description, `rdfs` is declared as a prefix in my ontology, but of course `rdfs:comment` is not explicitly declared in my ontology, because the rdfs properties (and other entities declared in widely used terminologies) should be recognized by Protege automatically.

![screenshot 2015-10-23 1030](https://cloud.githubusercontent.com/assets/2441046/10700403/5fdc8ec6-7972-11e5-9b46-28a3bc6caee0.png)

**Comment by csnyulas** [comment]
BTW, I agree with @martinjoconnor that the rdfs:label issue should be fixed. Maybe we should create a separate issue for it.

**Comment by martinjoconnor** [comment]
Agree that all the standard annotation properties should be handled irrespective of whether the relevant prefixes have been declared or not.

**Comment by johardi** [comment]
Could you list all the known annotation properties that Cellfie has to aware by default?

**Comment by csnyulas** [comment]
It should be the same that Protege knows about, but I don't know exactly how Protege decides about what prefixes, annotations or properties to consider as known. It must be somewhere in the Protege code or the configuration files.

**Comment by martinjoconnor** [comment]
Had a look but could not find a list. I would ask @matthewhorridge.

**Comment by csnyulas** [comment]
The OWL spec declares `rdf`, `rdfs`, `owl` and `xsd` as part of the OWL 2 reserved vocabulary that should be interpreted exactly as it is specified in Table 2:
http://www.w3.org/TR/owl2-syntax/#IRIs

The Manchester syntax also recognizes these special prefixes:
http://www.w3.org/2007/OWL/wiki/ManchesterSyntax#Ontologies_and_Annotations

I would expect that the OWL API would have some methods to deal with these special prefixes.

**Comment by johardi** [comment]
I have extended the known prefixes by using [Namespaces](http://owlcs.github.io/owlapi/apidocs_4_2_3/org/semanticweb/owlapi/vocab/Namespaces.html) from OWLAPI, which Protege uses this same Enum too.

I think by default Protege knows only a small list of annotation properties as the screenshot below. Other annotation properties must be entered manually I guess.

![screen shot 2016-05-02 at 4 32 30 pm](https://cloud.githubusercontent.com/assets/5062950/14971085/9ad1a388-1083-11e6-8e95-043ce52e030f.png)

**Comment by johardi** [comment]
I'm going to close this issue by splitting it into 2 separate issues: https://github.com/protegeproject/cellfie-plugin/issues/90 and https://github.com/protegeproject/cellfie-plugin/issues/91
