### ISSUE TITLE
Unable to set language in literals

### ISSUE THREAD

**Issue by nielsthinkiq** [protegeproject/cellfie-plugin#41]
Manchester Syntax specifies: 
     stringLiteralWithLanguage := quotedString languageTag

In the syntax I would typically set:
Individual: FamiliaSwissMuesliMixedCereals32OzBox
    Annotations: 
        skos:prefLabel "Familia Swiss Muesli Mixed Cereals - 32 oz box"@en

There is no way to set the language in the rules. All literals are set to ^^xsd:string

How do I do this?

**Comment by johardi** [comment]
Currently Cellfie does not support plain literal, as well as language tag. It supports only **typed** literals (however with limitation to integer, float, boolean and string).

We are labelling your report as a future enhancement for the next release.

**Comment by johardi** [comment]
So let me revise my answer. This issue is actually a bug: Cellfie _does_ support language tag, by using the directive `xml:lang`

So reusing your example the transformation rule should be written as:

```
Individual: @A1
Annotations: skos:prefLabel @A1(xml:lang="en")
```

where cell A1 contains the value "Familia Swiss Muesli Mixed Cereals - 32 oz box"

However, we found that rdf:PlainLiteral type is missing in the code and it breaks the directive validation method.

**Comment by nielsthinkiq** [comment]
Josef,

Thanks for the quick response.

Do you have any indication when this bug could be fixed by?

Thanks in advance,
Niels

**Comment by johardi** [comment]
Hi Niels,
very sorry for the late response. Currently we are arranging new timeline for the development iterations. I'm already in a new branch for supporting rdf:plainLiteral and hopefully we'll make a new release on February.

**Comment by nielsthinkiq** [comment]
Josef,

This is fantastic news. Thank you very much for your quick response.

Best regards,
Niels

**Comment by johardi** [comment]
Fix at https://github.com/protegeproject/mapping-master/commit/aaabfe65c83cc9c1ef59834cb09a068a7630225f
