### ISSUE TITLE
Version string in update document is invalid

### ISSUE THREAD

**Issue by matthewhorridge** [protegeproject/cellfie-plugin#42]
The plugin update document at https://raw.githubusercontent.com/protegeproject/cellfie-plugin/master/update-info/protege-5/update.properties contains an illegal version string (2.0.0-beta-6). 

You need to replace the dashes with dots I think.

**Comment by martinjoconnor** [comment]
FYI, seems happy if only first dash is replaced, e.g., 2.0.0.beta-6. Protege's plugin update code should probably handle the leading dash too (seems to be common, e.g., https://www.nuget.org/packages/Microsoft.AspNet.Mvc/6.0.0-beta8).

**Comment by johardi** [comment]
Fixed at https://github.com/protegeproject/cellfie-plugin/commit/849396dbc5c3b41354fe0f9dddb95170aae63914
I agree with @martinjoconnor though
