### ISSUE TITLE
Incorrect removal of "-" and "_"

### ISSUE THREAD

**Issue by nielsthinkiq** [protegeproject/cellfie-plugin#45]
I am trying to generate entities which has values such as "A_B_C" in the Excel spreadsheet, They are imported with names set to "ABC". The same is true for "A-B-C".

It seems illogical that the importer would strip off legal characters in entity names. 

Thanks in advance.

**Comment by martinjoconnor** [comment]
I am not sure what is going on here. Josef will likely answer.

However, I would strongly suggest using the rdfs:label of the OWL entity to store these meaningful names. I presume you are trying to use the entity IRI itself (the rdf:ID) to contain these names. rdfs:labels can contain arbitrary strings whereas IRIs have quite a few restrictions on the characters they contain.

To set the label of an entity use the rdfs:label directive in a reference, e.g.,

Class: @A5(rdfs:label=("Thing_", @A5, "_", @C*) )

FYI, in future I would suggest posting these types of language questions to the Protege mailing, where they will get more eyeballs. I have just added a link to the mailing list in the repo README:

https://github.com/protegeproject/cellfie-plugin#questions

**Comment by nielsthinkiq** [comment]
Thanks Martin,

Thanks for the link to the protege list. I am not sure if this is a protege question or a Cellfie question, but it looks more like a Cellfie question/issue.

Unfortunately it is not easy to do this. Quite often we have to refer to IDs that already exist and be able to do inferencing on that information. rdfs:label is an AnnotationProperty which is not used by the inferencer/reasoner.

The more constraints a tool like this imposes, the less valuable it becomes. Quite often we have to use a combination of tools and if each tool has its own constraints, then there will be no space left to maneuver on. It is best if the standards are followed and no further constraints are imposed.

I am looking forward to hearing from Josef.

**Comment by martinjoconnor** [comment]
Mapping Master should definitely not allow users to create invalid IRIs. These would break parsing, thus creating invalid ontologies.

However, I would argue that MM should probably throw an exception here rather than silently remapping characters. @johardi (and @matthewhorridge or @csnyulas) will likely have input here too.

**Comment by nielsthinkiq** [comment]
I agree that Mapping Master should not allow invalid IRIs to be created.

However, it is valid to use _ and - in IRIs.

Ref: In general URIs as defined by RFC 3986 (see Section 2: Characters) may contain any of the following characters: ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-._~:/?#[]@!$&'()*+,;=. Any other character needs to be encoded with the percent-encoding (%hh). Each part of the URI has further restrictions about what characters need to be represented by an percent-encoded word.

Protege also allows _ and - when I manually create names.

**Comment by johardi** [comment]
I've posted this as a new feature https://github.com/protegeproject/cellfie-plugin/issues/46
