### ISSUE TITLE
unexpected child node Reference for node Types

### ISSUE THREAD

**Issue by jmarinpsu** [protegeproject/cellfie-plugin#49]
The following works:

```
Individual: @A*(rdf:ID rdfs:label=@B*)
     Annotations: note @D*(xsd:string mm:SkipIfEmptyLocation)
```

But the following does not:

```
Individual: @A*(rdf:ID rdfs:label=@B*)
     Types: @C*
     Annotations: note @D*(xsd:string mm:SkipIfEmptyLocation)
```

Generates error:

> ![image](https://cloud.githubusercontent.com/assets/18313264/14327059/b386c384-fbfe-11e5-8d44-a7b1d993d135.png)

**Comment by jmarinpsu** [comment]
Figured out that I had to do the following:

```
Individual: @A*(rdf:ID rdfs:label=@B*)
     Types: (@C*)
     Annotations: note @D*(xsd:string mm:SkipIfEmptyLocation)
```

**Comment by martinjoconnor** [comment]
Reopening - you should not have needed parentheses to make this work.

**Comment by johardi** [comment]
Fixed via https://github.com/protegeproject/mapping-master/commit/e6a8ee85e0c172b0d28a7b1e67cdec361b7b0bb1
