### ISSUE TITLE
Problem creating named individuals using mm:hashEncode

### ISSUE THREAD

**Issue by nehajain10** [protegeproject/cellfie-plugin#51]
I want to create individuals using the input cell value from my excel sheet. For this I used mm:hashEncode option, as mentioned in the grocery tutorial. But the names are auto generated. Please let me know where I am going wrong.
![cellfie](https://cloud.githubusercontent.com/assets/17719801/14849970/a9ecbb80-0c93-11e6-95f1-6512210f253f.jpg)

**Comment by csnyulas** [comment]
The `mm:hashEnCode` option is the one saying that you want auto-generated meaningless identifiers, but such that they can be regenerated over and over again if you run Cellfie multiple times.

If you want to generate human readable names from the content of the cells, use one of the following options:

```
mm:noEncode
mm:camelCaseEncode
mm:snakeCaseEncode
```

or do not specify any option, which will do the default behavior (currently `mm:camelCaseEncode`)

Note: Use `mm:noEncode` only if the content of the cells can be part of valid IRI, i.e. do not contain restricted characters, such as space.
