### ISSUE TITLE
Allow the cancelation of the closing Cellfie operation

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/cellfie-plugin#63]
If one clicks on the "X" icon on the Cellfie window, in order to close it, and there were unsaved modifications to the rules, a dialog pops up to ask whether you want to save those changes or not. If the user chooses "Yes", the file that was loaded will be overwritten (or, if the rules were not loaded from a file, a new file will be created). If (s)he chooses "No", changes won't be saved. Currently there is no option to "Cancel" the operation, i.e. to go back to editing, in case the user would like to do some modifications to the rules before saving them, or (s)he wishes to save the new rules under a different file name.

Therefore, it would be really nice to add a "Cancel" option. Also, the "X" button on the "Closing Cellfie" dialog should have the "Cancel" behavior.

**Comment by johardi** [comment]
Closes via https://github.com/protegeproject/cellfie-plugin/commit/44ddf13886375e0f308e1411c8d0f6846cce069e
