### ISSUE TITLE
Name the offending entity on mismatch entity type

### ISSUE THREAD

**Issue by martinjoconnor** [protegeproject/cellfie-plugin#65]
Currently an error like the following is presented if the user tries to use an incorrect entity type in a transformation (e.g., reference refers to a class but there is an existing entity that is an individual).

![errorrule1](https://cloud.githubusercontent.com/assets/1731323/17541549/81803d6e-5e75-11e6-9529-7de029e04184.png)

It would be nice to list the entity name in the error.

**Comment by johardi** [comment]
Fix via https://github.com/protegeproject/mapping-master/commit/ba91c510283d686a0d7ed94bf2b654e6f4da97c9
