### ISSUE TITLE
Preview presents sheets in a different order than MS Excel

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/cellfie-plugin#66]
Sometimes, the Cellfie spreadsheet preview panel presents the sheets in a different order than the order they were created (by default) by Microsoft Excel.

The problem occurs with [this spreadsheet](https://github.com/protegeproject/cellfie-plugin/files/421064/Test.Cellfie.1.xlsx), which as created in MS Excel 2010 on Windows 7 when opened in Cellfie 2.0.0. **Observe that Sheet 2 is shown before Sheet 1.** All 3 sheets in the spreadsheets are the ones created by default by MS Excel.

![cellfietest_issue1](https://cloud.githubusercontent.com/assets/2441046/17711672/9004d2aa-63a7-11e6-9b3e-e7579ae9d95e.png)

**Comment by johardi** [comment]
Fix via https://github.com/protegeproject/mapping-master/commit/1ce94c80f27cb45ef0fef523d348fdae61250840
