### ISSUE TITLE
Ontology creation with log data

### ISSUE THREAD

**Issue by nehajain10** [protegeproject/cellfie-plugin#73]
I have a log generated through IDS. I want to create an ontology using log data. I believe that I should first convert the log to xml and then convert the xml to ontology. Does protege-5 provide any plugin for populating a skeleton ontology with instances picked from xml file?

**Comment by martinjoconnor** [comment]
Transforming the log to XML would complicate the translation process. I would transform it to a spreadsheet and then use Cellfie to to populate an OWL ontology with the contents.

(I wrote an experimental XML to OWL DSL a few years ago but it never reached release state. Even if it were available I'd recommend the spreadsheet route.)

**Comment by nehajain10** [comment]
Thank a lot for the valuable input . I will try doing it through Cellfie now.

**Comment by nehajain10** [comment]
But I also found this plugin called XML2OWL. But I could not find any manual about installing and using it. Is this tool supported by protege?

**Comment by martinjoconnor** [comment]
Link?

**Comment by nehajain10** [comment]
I got to know about this plugin from Protege import wiki
http://protegewiki.stanford.edu/wiki/Import
and downloaded the plugin from https://sourceforge.net/projects/xml2owl/
But could not find any manual for installing and using it.

**Comment by martinjoconnor** [comment]
It was last updated over three years ago so is unlikely to be available for the current Protege 5 release. You could email the developers and ask them about its current state.

However, unless your log files have some complex structural content I cannot see any advantage to going down the XML route. (Quite apart from the fact that using a plugin under active development is likely to be far less painful than using one that has not been updated in years.)

**Comment by jeffbjut** [comment]
I have a log generated through IDS. I want to create an ontology using log data. But I do not know how to build this ontology, may I give advice

**Comment by martinjoconnor** [comment]
I would post this question to the Protege mailing list, which has a pretty active community. 

https://protege.stanford.edu/support.php

I would also add some more details. The above question is a little general.

**Comment by jeffbjut** [comment]
First of all thank the professor for his reply. I want to use ontology to do the work is like this: There are some server logs, IDS logs, would like to use ontology to achieve the storage of these logs, so that I later retrieve these log analysis, but based on some log entries I build ontology The concept of division work without ideas, hope to be able to teach some advice!

**Comment by martinjoconnor** [comment]
I think you misunderstood my suggestion: I recommended posting your question to the Protege mailing list:

https://protege.stanford.edu/support.php
