### ISSUE TITLE
Shouldn't mm:uuidEncode generate the same UUID for a given cell even if it is referred from multiple rules?

### ISSUE THREAD

**Issue by csnyulas** [protegeproject/cellfie-plugin#78]
Say I have two rules:

```
Indivdual: @B*(mm:uuidEncode)
    Types: @B1
```

and

```
Individual: @A*
    Facts: @B*(mm:uuidEncode)
```

At the moment these two rules generate two sets of different individuals from the `@B*` cells, which is probably not the desired behaviour (i.e. the individual created by the first rule from a given cell is not the same as the individual created by the second rule from the same cell). A solution for such cases would be to use `mm:locationEncode`, but this is not implemented yet.
The most important thing, however, is that we decide what is the "correct" behaviour, and we need to make sure that it is implemented and documented correctly.

**Comment by martinjoconnor** [comment]
Yes, it should resolve to the same value.

A reference consists of a location plus explicit and implicit directives:

```
@<location>(<explicit_directives> <implicit_directives>)
```

The implicit directives are supplied from global directive defaults (e.g., <tt>mm:defaultShiftsetting</tt>). 

A reference with the same directives (and any parameters for those directives) and with the same current location should resolve identically for any expression that it is used in <i>in the same ruleset run</i>. 

In the original MM I had a map of references to resolved values. So, if reference <tt>@A3(mmm:uuidEncode)</tt> was used in one  rule and then the same reference was used in another I would simply use the value from the map.

This has always been a key design decision in MM - but one that I am not sure I ever documented anywhere. I will be documenting this stuff soon as discussed.

**Comment by csnyulas** [comment]
Thanks for the clarification. So this is a bug then. I will label it as such.

**Comment by martinjoconnor** [comment]
Note that the Java class representing a reference has <tt>hashCode</tt> and <tt>equal</tt> implemented so can be used as a key for a map. The implementation should probably be double checked to ensure that they consider all reference state. (I usually just let IntelliJ generate handle the generation of these methods.)

The guarantee of a unique value per reference only applies across a set of rules in a single run. There is no uniqueness guarantee across runs - though clearly for rules that have no UUID-encoding the same rules should generate the same results for an identical ontology with the same global defaults. 

Which is a long way of saying the reference cache should be emptied before each run.

**Comment by csnyulas** [comment]
That's right. The bug is that at the moment even within the same run of a ruleset, different rules generate different UUIDs for the cell. I tested it last night, and I can confirm.

**Comment by johardi** [comment]
Fix via https://github.com/protegeproject/mapping-master/commit/fc06a4f1a7d82484caa717487ffcdca5e6b778ee

**Comment by csnyulas** [comment]
A note to @martinjoconnor: We looked with @johardi at the code, and the location map that you were using to retrieve previously resolved references, uses `SpreadsheetLocation`s as keys not the `ReferenceNode`s (the one that would contain all the directives as parameters), so any cell reference that resolves to the same cell after directives being applied, would get the same IRI with UUID-encoding _within a single run of the mappings (or potentially even of Protégé)_.

See: https://github.com/protegeproject/mapping-master/blob/fc06a4f1a7d82484caa717487ffcdca5e6b778ee/src/main/java/org/mm/renderer/owlapi/OWLReferenceRenderer.java#L323
